variables:
  GIT_SSL_NO_VERIFY: "true"
  DOCKER_IMAGE_VERSION: "1.0.0"

stages :
 - build
 - test
 - deploy

build_go:
 stage: build
 image: golang:1.9.2
 script:
  - go build

test_go:
 stage: test
 image: golang:1.9.2
 script:
  - go test

deploy_docker_image:
  stage: build
  image: docker:latest
  script:
   - docker login registry.beaverhosting.fr -u testuser -p $REGISTRY_PASSWORD
   - docker image build -t bh-p-hello-world .
   - docker tag bh-p-hello-world registry.beaverhosting.fr/bh-p-hello-world:$DOCKER_IMAGE_VERSION
   - docker push registry.beaverhosting.fr/bh-p-hello-world:$DOCKER_IMAGE_VERSION