variables:
  GIT_SSL_NO_VERIFY: "true"

stages :
 - build
 - test
 - deploy

build_go:
 stage: build
 image: golang:1.9.2
 script:
  - go build

test_go:
 stage: test
 image: golang:1.9.2
 script:
  - go test
 dependencies:
  - build_go

deploy_docker_image:
  stage: deploy
  image: docker:latest
  script:
   - docker login registry.beaverhosting.fr -u testuser -p testpassword
   - docker image build -t bh-p-hello-world .
   - docker tag bh-p-hello-world registry.beaverhosting.fr/bh-p-hello-world:1.0.0
   - docker push registry.beaverhosting.fr/bh-p-hello-world:1.0.0
  when: manual
