variables:
  GIT_SSL_NO_VERIFY: "false"

stages :
 - build
 - test
 - deploy

build_go:
 stage: build
 image: golang:1.9.2
 script:
  - go build

test_go:
 stage: test
 image: golang:1.9.2
 script:
  - go test
 dependencies:
  - build_go

deploy_docker_image:
  stage: deploy
  image: docker:latest
  script:
   - docker login $REGISTRY_URL -u $REGISTRY_LOGIN -p $REGISTRY_PASSWORD
   - docker image build -t hello-world .
   - docker tag hello-world $REGISTRY_URL/hello-world:1.0.0
   - docker push $REGISTRY_URL/hello-world:1.0.0
   - docker tag hello-world $REGISTRY_URL/hello-world:latest
   - docker push $REGISTRY_URL/hello-world:latest
  when: manual
