apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world
data:
  MY_CUSTOMER_NAME: "Jean Kevin"
---
kind: Service
apiVersion: v1
metadata:
  name: hello-world
spec:
  selector:
    app: hello-world
  ports:
  - protocol: TCP
    port: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: registry.beaverhosting.fr/hello-world:latest
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: hello-world
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        livenessProbe:
         httpGet:
           path: /alive
           port: 8080
         initialDelaySeconds: 15
         periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /alive
            port: 8080
      imagePullSecrets:
        - name: registrykey