apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  selector:
    app: hello-world
  ports:
  - protocol: TCP
    port: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: registry.beaverhosting.fr/hello-world:latest
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: hello-world
        env:
          - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      imagePullSecrets:
        - name: registrykey